[package]
name = "pipeline-api"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Pipeline step implementations"

[dependencies]
pipeline-spi = { path = "../pipeline-spi" }
pipeline-core = { path = "../pipeline-core" }
thiserror = { workspace = true }
serde = { workspace = true }
