[package]
name = "optimizer-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Optimizer Core - implementations of optimization algorithms"

[dependencies]
optimizer-spi = { path = "../optimizer-spi" }
optimizer-api = { path = "../optimizer-api" }
indicator-core = { path = "../../indicator/indicator-core" }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
rayon = "1.10"
