[package]
name = "tuning-api"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hyperparameter tuning API - configs and builders"

[dependencies]
tuning-spi = { path = "../tuning-spi" }
indicator-spi = { path = "../../indicator/indicator-spi" }
indicator-api = { path = "../../indicator/indicator-api" }
serde.workspace = true
